import type { InventoryCarRecord } from './types'

const now = '2026-07-17T15:00:00.000Z'

const l200Description = {
  uk: `2024 Mitsubishi L200 GL DC 2.4L 4WD Diesel 5MT. STOCK# RH032499. Euro 2, LHD, Antwerp Belgium. Пробіг 10 Mi. Білий / чорний салон. Easy Select 4WD, A/C, ABS, ASTC, HSA, ESS, іммобілайзер, SRS (водій), сталеві диски 16". Market Restriction: NAFTA & Restricted Countries.`,
  pl: `2024 Mitsubishi L200 GL DC 2.4L 4WD Diesel 5MT. STOCK# RH032499. Euro 2, LHD, Antwerp Belgium. Przebieg 10 Mi. Biały / czarne wnętrze. Easy Select 4WD, A/C, ABS, ASTC, HSA, ESS, immobiliser, SRS (kierowca), felgi stalowe 16". Market Restriction: NAFTA & Restricted Countries.`,
  en: `2024 Mitsubishi L200 GL DC 2.4L 4WD Diesel 5MT. STOCK# RH032499 Available. Euro 2, LHD, EXW Antwerp Belgium AET. Mileage 10 Mi (16.09 Km). Engine 2,498cc, 5-Speed MT, Pick-Up, Diesel, White / Black. Equipment: Easy Select 4WD, Halogen headlights, A/C Cooler, ASTC, HSA, ESS, ABS, EBD, immobilizer, SRS airbag (Driver), 16" steel wheels. Market Restriction: NAFTA & Restricted Countries.`,
}

const landtrekDescription = {
  uk: `2026 Peugeot Landtrek Double Cab N2 Top Spec 4x4 2.2L Turbodiesel 8-Speed AT 200 bhp / 450 Nm. STOCK# T3033149. Euro 6.3, LHD, Belgium. Пробіг 10 Mi. Білий. Diff lock, payload 1 085 kg, 18" alloy, навігація, 10" HD touch, BSM, lane assist, 360°, підігрів дзеркал, датчики паркування, hands-free.`,
  pl: `2026 Peugeot Landtrek Double Cab N2 Top Spec 4x4 2.2L Turbodiesel 8-Speed AT 200 bhp / 450 Nm. STOCK# T3033149. Euro 6.3, LHD, Belgium. Przebieg 10 Mi. Biały. Diff lock, payload 1 085 kg, 18" alloy, nawigacja, 10" HD touch, BSM, lane assist, 360°, podgrzewane lusterka, czujniki parkowania, hands-free.`,
  en: `2026 Peugeot Landtrek Double Cab N2 Top Spec 4x4 2.2L Turbodiesel 8-Speed AT 200bhp w/ 450NM Torque. STOCK# T3033149 Available. Euro 6.3, LHD, EXW Belgium. Mileage 10 Mi (16.09 Km). Engine 2184cc, AT, Pick up, 4WD Diesel, White. REAR FINAL DRIVE DIFFERENTIAL LOCKING, PAYLOAD 1,085 KG, 18 INCH ALLOY, NAVIGATION, 10-INCH HD TOUCH, BLIND SPOT + LANE CHANGE ASSIST, DIGITAL PANORAMIC VISUAL ASSISTANCE, HANDS-FREE ACCESS/STARTING.`,
}

const priusDescription = {
  uk: `Toyota Prius в наявності. Об'єм двигуна 1798 см³. Перша реєстрація 11.02.2010. Максимальна швидкість 180 км/год. Кількість місць: 5. Екологічний стандарт Euro 5L. Місцезнаходження: Польща. Ціна: 24 000 zł.`,
  pl: `Toyota Prius dostępna. Pojemność silnika 1798 cm³. Pierwsza rejestracja 11.02.2010. Prędkość maksymalna 180 km/h. Liczba miejsc: 5. Norma Euro 5L. Lokalizacja: Polska. Cena: 24 000 zł.`,
  en: `Toyota Prius in stock. Engine 1798 cc. First registration 11.02.2010. Top speed 180 km/h. Seats: 5. Euro 5L. Location: Poland. Price: 24 000 zł.`,
}

export const DEFAULT_SEED_CARS: InventoryCarRecord[] = [
  {
    id: 'mitsubishi-l200-2024-1',
    image: '/cars/mitsubishi-l200-1a.jpg',
    images: ['/cars/mitsubishi-l200-1a.jpg', '/cars/mitsubishi-l200-1b.jpg'],
    make: 'Mitsubishi',
    model: 'L200 GL DC 2.4L 4WD',
    year: 2024,
    engine: '2.4L Diesel · 2498cc',
    mileage: '10 Mi (16 km)',
    gearboxKey: 'manual',
    price: 'За запитом',
    statusKey: 'delivered',
    route: { uk: 'Бельгія → PL', pl: 'Belgia → PL', en: 'Belgium → PL' },
    bodyClass: { uk: 'Пікап', pl: 'Pick-up', en: 'Pick-Up' },
    description: l200Description,
    formatKey: 'turnkey',
    resultKey: 'keysInPl',
    published: true,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'mitsubishi-l200-2024-2',
    image: '/cars/mitsubishi-l200-2a.jpg',
    images: ['/cars/mitsubishi-l200-2a.jpg', '/cars/mitsubishi-l200-2b.jpg'],
    make: 'Mitsubishi',
    model: 'L200 GL DC 2.4L 4WD',
    year: 2024,
    engine: '2.4L Diesel · 2498cc',
    mileage: '10 Mi (16 km)',
    gearboxKey: 'manual',
    price: 'За запитом',
    statusKey: 'delivered',
    route: { uk: 'Бельгія → PL', pl: 'Belgia → PL', en: 'Belgium → PL' },
    bodyClass: { uk: 'Пікап', pl: 'Pick-up', en: 'Pick-Up' },
    description: l200Description,
    formatKey: 'turnkey',
    resultKey: 'keysInPl',
    published: true,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'mitsubishi-l200-2024-3',
    image: '/cars/mitsubishi-l200-3a.jpg',
    images: [
      '/cars/mitsubishi-l200-3a.jpg',
      '/cars/mitsubishi-l200-3b.jpg',
      '/cars/mitsubishi-l200-3c.jpg',
    ],
    make: 'Mitsubishi',
    model: 'L200 GL DC 2.4L 4WD',
    year: 2024,
    engine: '2.4L Diesel · 2498cc',
    mileage: '10 Mi (16 km)',
    gearboxKey: 'manual',
    price: 'За запитом',
    statusKey: 'delivered',
    route: { uk: 'Бельгія → PL', pl: 'Belgia → PL', en: 'Belgium → PL' },
    bodyClass: { uk: 'Пікап', pl: 'Pick-up', en: 'Pick-Up' },
    description: l200Description,
    formatKey: 'turnkey',
    resultKey: 'keysInPl',
    published: true,
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'peugeot-landtrek-2026',
    image: '/cars/peugeot-landtrek-1.jpg',
    images: ['/cars/peugeot-landtrek-1.jpg', '/cars/peugeot-landtrek-2.jpg'],
    make: 'Peugeot',
    model: 'Landtrek Double Cab N2 Top Spec',
    year: 2026,
    engine: '2.2L TD · 2184cc · 200hp',
    mileage: '10 Mi (16 km)',
    gearboxKey: 'automatic',
    price: 'За запитом',
    statusKey: 'delivered',
    route: { uk: 'Бельгія → PL', pl: 'Belgia → PL', en: 'Belgium → PL' },
    bodyClass: { uk: 'Пікап', pl: 'Pick-up', en: 'Pick up' },
    description: landtrekDescription,
    formatKey: 'turnkey',
    resultKey: 'keysInPl',
    published: true,
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'toyota-prius-2010',
    image: '/cars/toyota-prius.jpg',
    images: ['/cars/toyota-prius.jpg'],
    make: 'Toyota',
    model: 'Prius',
    year: 2010,
    engine: '1798 см³',
    mileage: '—',
    gearboxKey: 'automatic',
    price: '24 000 zł',
    statusKey: 'delivered',
    route: { uk: 'Польща', pl: 'Polska', en: 'Poland' },
    bodyClass: { uk: 'Хетчбек', pl: 'Hatchback', en: 'Hatchback' },
    description: priusDescription,
    formatKey: 'turnkey',
    resultKey: 'keysInPl',
    published: true,
    sortOrder: 5,
    createdAt: now,
    updatedAt: now,
  },
]
